language: python
python:
  - "2.7"
services:
  - mongodb
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
# command to run tests
script: python unittest.py

repo_token: jwuBEFj3CrdxZymzLSTEnS9sMFgBIecyU
service_name: travis-ci

paralell : True

notifications:
  email:
    - davidawad64@gmail.com
