language: python

env:
  DEBUG: True

before_install:
  - docker-compose up --build

  # You will want this for logging. If one of your containers does not build for
  # whatever reason it's best to report that now before your tests start
  # otherwise it can be really tricky to debug why tests are failing sometimes.
  - docker ps

services:
  - docker

script:
  - python tests/unittest.py

after_success: coveralls --verbose
