language: python
python:
  - 2.7
services:
  - mongodb
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install coveralls
  
# command to run tests
script:   
  - python unittest.py
  - coverage run --source=coveralls unittest.py
  - coverage report -m

notifications:
  email:
    - davidawad64@gmail.com

after_success: coveralls --verbose
